CHARACTERS_MAP = {
    "2b": ("nier_automata", "nier:automata", "nier:automata", "2b"),
    "tifa lockhart": ("final_fantasy_vii", "final_fantasy_vii", "final_fantasy_vii", "tifa_lockhart"),
    "loona": ("helluva_boss", "helluva_boss", "helluva_boss", "loona"),
    "raiden shogun": ("genshin_impact", "genshin_impact", "genshin_impact", "raiden_shogun"),
    "ei": ("genshin_impact", "genshin_impact", "genshin_impact", "raiden_shogun"),
    "firefly": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "firefly"),
    "makima": ("chainsaw_man", "chainsaw_man", "chainsaw_man", "makima"),
    "power": ("chainsaw_man", "chainsaw_man", "chainsaw_man", "power"),
    "kafka": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "kafka"),
    "acheron": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "acheron"),
    "hu tao": ("genshin_impact", "genshin_impact", "genshin_impact", "hu_tao"),
    "ganyu": ("genshin_impact", "genshin_impact", "genshin_impact", "ganyu"),
    "furina": ("genshin_impact", "genshin_impact", "genshin_impact", "furina"),
    "arlecchino": ("genshin_impact", "genshin_impact", "genshin_impact", "arlecchino"),
    "navia": ("genshin_impact", "genshin_impact", "genshin_impact", "navia"),
    "yor forger": ("spy_x_family", "spy_x_family", "spy_x_family", "yor_forger"),
    "grace howard": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "grace_howard"),
    "ellen joe": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "ellen_joe"),
    "zhu yuan": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "zhu_yuan"),
    "jinhsi": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "jinhsi"),
    "changli": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "changli"),
    "yinlin": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "yinlin"),
    "marin kitagawa": ("sono_bisque_doll_wa_koi_wo_suru", "my_dress-up_darling", "my_dress-up_darling", "kitagawa_marin"),
    "kitagawa marin": ("sono_bisque_doll_wa_koi_wo_suru", "my_dress-up_darling", "my_dress-up_darling", "kitagawa_marin"),
    "zero two": ("darling_in_the_franxx", "darling_in_the_franxx", "darling_in_the_franxx", "zero_two"),
    "asuka langley": ("neon_genesis_evangelion", "neon_genesis_evangelion", "neon_genesis_evangelion", "asuka_langley"),
    "rei ayanami": ("neon_genesis_evangelion", "neon_genesis_evangelion", "neon_genesis_evangelion", "ayanami_rei"),
    "widowmaker": ("overwatch", "overwatch", "overwatch", "widowmaker"),
    "mercy": ("overwatch", "overwatch", "overwatch", "mercy"),
    "d.va": ("overwatch", "overwatch", "overwatch", "d.va"),
    "tracer": ("overwatch", "overwatch", "overwatch", "tracer"),
    "keqing": ("genshin_impact", "genshin_impact", "genshin_impact", "keqing"),
    "shenhe": ("genshin_impact", "genshin_impact", "genshin_impact", "shenhe"),
    "yelan": ("genshin_impact", "genshin_impact", "genshin_impact", "yelan"),
    "nilou": ("genshin_impact", "genshin_impact", "genshin_impact", "nilou"),
    "black swan": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "black_swan"),
    "jade": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "jade"),
    "robin": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "robin"),
    "sparkle": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "sparkle"),
    "judy hopps": ("zootopia", "zootopia", "zootopia", "judy_hopps"),
    "princess zelda": ("the_legend_of_zelda", "the_legend_of_zelda", "the_legend_of_zelda", "princess_zelda"),
    "midna": ("the_legend_of_zelda", "the_legend_of_zelda", "the_legend_of_zelda", "midna"),
    "samus aran": ("metroid", "metroid", "metroid", "samus_aran"),
    "lara croft": ("tomb_raider", "tomb_raider", "tomb_raider", "lara_croft"),
    "jessica rabbit": ("who_framed_roger_rabbit", "who_framed_roger_rabbit", "who_framed_roger_rabbit", "jessica_rabbit"),
    "gwen tennyson": ("ben_10", "ben_10", "ben_10", "gwen_tennyson"),
    "lopunny": ("pokemon", "pokemon", "pokemon", "lopunny"),
    "gardevoir": ("pokemon", "pokemon", "pokemon", "gardevoir"),
    "lucario": ("pokemon", "pokemon", "pokemon", "lucario"),
    "vaporeon": ("pokemon", "pokemon", "pokemon", "vaporeon"),
    "sylveon": ("pokemon", "pokemon", "pokemon", "sylveon"),
    "cynthia": ("pokemon", "pokemon", "pokemon", "cynthia"),
    "marnie": ("pokemon", "pokemon", "pokemon", "marnie"),
    "rouge the bat": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "rouge_the_bat"),
    "amy rose": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "amy_rose"),
    "blaze the cat": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "blaze_the_cat"),
    "twilight sparkle": ("my_little_pony", "my_little_pony", "my_little_pony", "twilight_sparkle"),
    "fluttershy": ("my_little_pony", "my_little_pony", "my_little_pony", "fluttershy"),
    "rarity": ("my_little_pony", "my_little_pony", "my_little_pony", "rarity"),
    "rainbow dash": ("my_little_pony", "my_little_pony", "my_little_pony", "rainbow_dash"),
    "pinkie pie": ("my_little_pony", "my_little_pony", "my_little_pony", "pinkie_pie"),
    "applejack": ("my_little_pony", "my_little_pony", "my_little_pony", "applejack"),
    "lois griffin": ("family_guy", "family_guy", "family_guy", "lois_griffin"),
    "meg griffin": ("family_guy", "family_guy", "family_guy", "meg_griffin"),
    "kim possible": ("kim_possible", "kim_possible", "kim_possible", "kim_possible"),
    "shego": ("kim_possible", "kim_possible", "kim_possible", "shego"),
    "starfire": ("teen_titans", "teen_titans", "teen_titans", "starfire"),
    "raven": ("teen_titans", "teen_titans", "teen_titans", "raven"),
    "velma dinkley": ("scooby-doo", "scooby-doo", "scooby-doo", "velma_dinkley"),
    "daphne blake": ("scooby-doo", "scooby-doo", "scooby-doo", "daphne_blake"),
    # Продолжение топа
    "ayaka": ("genshin_impact", "genshin_impact", "genshin_impact", "kamisato_ayaka"),
    "kamisato ayaka": ("genshin_impact", "genshin_impact", "genshin_impact", "kamisato_ayaka"),
    "yoimiya": ("genshin_impact", "genshin_impact", "genshin_impact", "yoimiya"),
    "kokomi": ("genshin_impact", "genshin_impact", "genshin_impact", "sangonomiya_kokomi"),
    "sangonomiya kokomi": ("genshin_impact", "genshin_impact", "genshin_impact", "sangonomiya_kokomi"),
    "mona": ("genshin_impact", "genshin_impact", "genshin_impact", "mona"),
    "jean": ("genshin_impact", "genshin_impact", "genshin_impact", "jean"),
    "lisa": ("genshin_impact", "genshin_impact", "genshin_impact", "lisa"),
    "eula": ("genshin_impact", "genshin_impact", "genshin_impact", "eula"),
    "rosaria": ("genshin_impact", "genshin_impact", "genshin_impact", "rosaria"),
    "fischl": ("genshin_impact", "genshin_impact", "genshin_impact", "fischl"),
    "barbara": ("genshin_impact", "genshin_impact", "genshin_impact", "barbara"),
    "ningguang": ("genshin_impact", "genshin_impact", "genshin_impact", "ningguang"),
    "beidou": ("genshin_impact", "genshin_impact", "genshin_impact", "beidou"),
    "signora": ("genshin_impact", "genshin_impact", "genshin_impact", "signora"),
    "yae miko": ("genshin_impact", "genshin_impact", "genshin_impact", "yae_miko"),
    "klee": ("genshin_impact", "genshin_impact", "genshin_impact", "klee"),
    "qiqi": ("genshin_impact", "genshin_impact", "genshin_impact", "qiqi"),
    "amber": ("genshin_impact", "genshin_impact", "genshin_impact", "amber"),

    # Honkai: Star Rail — продолжение топа
    "stelle": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "stelle"),
    "seele": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "seele"),
    "bronya": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "bronya"),
    "himeko": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "himeko"),
    "march 7th": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "march_7th"),
    "tingyun": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "tingyun"),
    "silver wolf": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "silver_wolf"),
    "ruan mei": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "ruan_mei"),
    "herta": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "herta"),
    "asta": ("honkai:_star_rail", "honkai:_star_rail", "honkai:_star_rail", "asta"),

    # Zenless Zone Zero — полный актуальный топ 2025
    "nicole demara": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "nicole_demara"),
    "anby demara": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "anby_demara"),
    "billy kid": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "billy_kid"),
    "corin wickes": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "corin_wickes"),
    "jane doe": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "jane_doe"),
    "qingyi": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "qingyi"),
    "seth lowell": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "seth_lowell"),
    "rina": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "alexandrina_sebastiane"),  
    "alexandrina sebastiane": ("zenless_zone_zero", "zenless_zone_zero", "zenless_zone_zero", "alexandrina_sebastiane"),
    "trigger":("zenless_zone_zero","zenless_zone_zero","zenless_zone_zero","trigger"),

    # Wuthering Waves — топ 2025
    "yinlin": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "yinlin"),
    "baizhi": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "baizhi"),
    "yangyang": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "yangyang"),
    "chixia": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "chixia"),
    "encore": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "encore"),
    "sanhua": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "sanhua"),
    "taoqi": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "taoqi"),
    "camellya": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "camellya"),
    "cartethyia": ("wuthering_waves", "wuthering_waves", "wuthering_waves", "cartethyia"),

    # Классика и другие топы
    "himiko toga": ("boku_no_hero_academia", "boku_no_hero_academia", "boku_no_hero_academia", "toga_himiko"),
    "toga himiko": ("boku_no_hero_academia", "boku_no_hero_academia", "boku_no_hero_academia", "toga_himiko"),
    "ochaco uraraka": ("boku_no_hero_academia", "boku_no_hero_academia", "boku_no_hero_academia", "uraraka_ochako"),
    "tsuyu asui": ("boku_no_hero_academia", "boku_no_hero_academia", "boku_no_hero_academia", "asui_tsuyu"),
    "momo yaoyorozu": ("boku_no_hero_academia", "boku_no_hero_academia", "boku_no_hero_academia", "yaoyorozu_momo"),
    "nami": ("one_piece", "one_piece", "one_piece", "nami"),
    "nico robin": ("one_piece", "one_piece", "one_piece", "nico_robin"),
    "yamato": ("one_piece", "one_piece", "one_piece", "yamato"),
    "boa hancock": ("one_piece", "one_piece", "one_piece", "boa_hancock"),
    "bulma": ("dragon_ball", "dragon_ball", "dragon_ball", "bulma"),
    "android 18": ("dragon_ball", "dragon_ball", "dragon_ball", "android_18"),
    "chi-chi": ("dragon_ball", "dragon_ball", "dragon_ball", "chi-chi"),
    "erza scarlet": ("fairy_tail", "fairy_tail", "fairy_tail", "erza_scarlet"),
    "lucy heartfilia": ("fairy_tail", "fairy_tail", "fairy_tail", "lucy_heartfilia"),
    # ... (ещё ~300 в этой части — классика вроде Touhou, Fate, Vocaloid и т.д.)
    "rem": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "rem"),
    "ram": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "ram"),
    "emilia": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "emilia"),
    "hatsune miku": ("vocaloid", "vocaloid", "vocaloid", "hatsune_miku"),
    "cirno": ("touhou", "touhou", "touhou", "cirno"),
    "flandre scarlet": ("touhou", "touhou", "touhou", "flandre_scarlet"),
    "sakuya izayoi": ("touhou", "touhou", "touhou", "sakuya_izayoi"),
    "marisa kirisame": ("touhou", "touhou", "touhou", "marisa_kirisame"),
    "reimu hakurei": ("touhou", "touhou", "touhou", "hakurei_reimu"),
        # Часть 3 — классика и средний топ
    "nezuko kamado": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kamado_nezuko"),
    "kamado nezuko": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kamado_nezuko"),
    "shinobu kocho": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kochou_shinobu"),
    "kocho shinobu": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kochou_shinobu"),
    "mitsuri kanroji": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kanroji_mitsuri"),
    "kanroji mitsuri": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kanroji_mitsuri"),
    "daki": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "daki"),
    "aoi kanzaki": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "kanzaki_aoi"),
    "kanao tsuyuri": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "tsuyuri_kanao"),
    "tamayo": ("kimetsu_no_yaiba", "kimetsu_no_yaiba", "kimetsu_no_yaiba", "tamayo"),

    # Fate series — топ waifu
    "saber": ("fate/stay_night", "fate_series", "fate_series", "saber"),
    "artoria pendragon": ("fate/stay_night", "fate_series", "fate_series", "artoria_pendragon"),
    "rin tosaka": ("fate/stay_night", "fate_series", "fate_series", "tosaka_rin"),
    "tosaka rin": ("fate/stay_night", "fate_series", "fate_series", "tosaka_rin"),
    "sakura matou": ("fate/stay_night", "fate_series", "fate_series", "matou_sakura"),
    "matou sakura": ("fate/stay_night", "fate_series", "fate_series", "matou_sakura"),
    "mash kyrielight": ("fate/grand_order", "fate_grand_order", "fate_grand_order", "mash_kyrielight"),
    "jeanne d'arc": ("fate/apocrypha", "fate_series", "fate_series", "jeanne_d'arc"),
    "scathach": ("fate/grand_order", "fate_grand_order", "fate_grand_order", "scathach"),
    "tamamo no mae": ("fate/extra", "fate_series", "fate_series", "tamamo_no_mae"),
    "astolfo": ("fate/apocrypha", "fate_series", "fate_series", "astolfo"),

    # Naruto / Boruto
    "hinata hyuga": ("naruto", "naruto", "naruto", "hyuga_hinata"),
    "hyuga hinata": ("naruto", "naruto", "naruto", "hyuga_hinata"),
    "sakura haruno": ("naruto", "naruto", "naruto", "haruno_sakura"),
    "haruno sakura": ("naruto", "naruto", "naruto", "haruno_sakura"),
    "tsunade": ("naruto", "naruto", "naruto", "tsunade"),
    "ino yamanaka": ("naruto", "naruto", "naruto", "yamanaka_ino"),
    "temari": ("naruto", "naruto", "naruto", "temari"),
    "tenten": ("naruto", "naruto", "naruto", "tenten"),
    "sarada uchiha": ("boruto", "boruto", "boruto", "uchiha_sarada"),
    "himawari uzumaki": ("boruto", "boruto", "boruto", "uzumaki_himawari"),

    # Bleach
    "rangiku matsumoto": ("bleach", "bleach", "bleach", "matsumoto_rangiku"),
    "matsumoto rangiku": ("bleach", "bleach", "bleach", "matsumoto_rangiku"),
    "orihime inoue": ("bleach", "bleach", "bleach", "inoue_orihime"),
    "inoue orihime": ("bleach", "bleach", "bleach", "inoue_orihime"),
    "ruka urahara": ("bleach", "bleach", "bleach", "urahara_rukia"),
    "rukia kuchiki": ("bleach", "bleach", "bleach", "kuchiki_rukia"),
    "kuchiki rukia": ("bleach", "bleach", "bleach", "kuchiki_rukia"),
    "yoroichi shihouin": ("bleach", "bleach", "bleach", "shihouin_yoruichi"),
    "shihouin yoruichi": ("bleach", "bleach", "bleach", "shihouin_yoruichi"),
    "nelliel tu odelschwanck": ("bleach", "bleach", "bleach", "nelliel_tu_odelschwanck"),

    # One Piece — продолжение
    "vivi nefertari": ("one_piece", "one_piece", "one_piece", "nefertari_vivi"),
    "nefertari vivi": ("one_piece", "one_piece", "one_piece", "nefertari_vivi"),
    "reiju vinsmoke": ("one_piece", "one_piece", "one_piece", "vinsmoke_reiju"),
    "vinsmoke reiju": ("one_piece", "one_piece", "one_piece", "vinsmoke_reiju"),
    "carrot": ("one_piece", "one_piece", "one_piece", "carrot"),
    "shirahoshi": ("one_piece", "one_piece", "one_piece", "shirahoshi"),

    # Dragon Ball — продолжение
    "videl": ("dragon_ball", "dragon_ball", "dragon_ball", "videl"),
    "caulifla": ("dragon_ball", "dragon_ball", "dragon_ball", "caulifla"),
    "kale": ("dragon_ball", "dragon_ball", "dragon_ball", "kale"),
    "android 21": ("dragon_ball", "dragon_ball", "dragon_ball", "android_21"),

    # Touhou Project — топ
    "remilia scarlet": ("touhou", "touhou", "touhou", "remilia_scarlet"),
    "flandre scarlet": ("touhou", "touhou", "touhou", "flandre_scarlet"),
    "patchouli knowledge": ("touhou", "touhou", "touhou", "patchouli_knowledge"),
    "sakuya izayoi": ("touhou", "touhou", "touhou", "sakuya_izayoi"),
    "youmu konpaku": ("touhou", "touhou", "touhou", "konpaku_youmu"),
    "yuyuko saigyouji": ("touhou", "touhou", "touhou", "saigyouji_yuyuko"),
    "reimu hakurei": ("touhou", "touhou", "touhou", "hakurei_reimu"),
    "marisa kirisame": ("touhou", "touhou", "touhou", "kirisame_marisa"),
    "cirno": ("touhou", "touhou", "touhou", "cirno"),
    "alice margatroid": ("touhou", "touhou", "touhou", "margatroid_alice"),

    # Vocaloid
    "hatsune miku": ("vocaloid", "vocaloid", "vocaloid", "hatsune_miku"),
    "kagamine rin": ("vocaloid", "vocaloid", "vocaloid", "kagamine_rin"),
    "kagamine len": ("vocaloid", "vocaloid", "vocaloid", "kagamine_len"),
    "megurine luka": ("vocaloid", "vocaloid", "vocaloid", "megurine_luka"),
    "meiko": ("vocaloid", "vocaloid", "vocaloid", "meiko"),
    "kaito": ("vocaloid", "vocaloid", "vocaloid", "kaito"),

    # Overwatch 2 new & classic
    "kiriko": ("overwatch", "overwatch", "overwatch", "kiriko"),
    "juno": ("overwatch", "overwatch", "overwatch", "juno"),
    "sojourn": ("overwatch", "overwatch", "overwatch", "sojourn"),
    "brigitte": ("overwatch", "overwatch", "overwatch", "brigitte"),
    "ana": ("overwatch", "overwatch", "overwatch", "ana"),
    "symmetra": ("overwatch", "overwatch", "overwatch", "symmetra"),
    "pharah": ("overwatch", "overwatch", "overwatch", "pharah"),
    "sombra": ("overwatch", "overwatch", "overwatch", "sombra"),

    # Pokémon trainers & others
    "may": ("pokemon", "pokemon", "pokemon", "may"),
    "dawn": ("pokemon", "pokemon", "pokemon", "dawn"),
    "hilda": ("pokemon", "pokemon", "pokemon", "hilda"),
    "rosa": ("pokemon", "pokemon", "pokemon", "rosa"),
    "serena": ("pokemon", "pokemon", "pokemon", "serena"),
    "lillie": ("pokemon", "pokemon", "pokemon", "lillie"),
    "misty": ("pokemon", "pokemon", "pokemon", "misty"),
    "jessie": ("pokemon", "pokemon", "pokemon", "jessie"),
    "bea": ("pokemon", "pokemon", "pokemon", "bea"),
    "nemona": ("pokemon", "pokemon", "pokemon", "nemona"),
    "penny": ("pokemon", "pokemon", "pokemon", "penny"),
    "mela": ("pokemon", "pokemon", "pokemon", "mela"),

    # Re:Zero, Konosuba, etc.
    "rem": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "rem"),
    "ram": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "ram"),
    "emilia": ("re:zero_kara_hajimeru_isekai_seikatsu", "re:zero", "re:zero", "emilia"),
    "aqua": ("kono_subarashii_sekai_ni_shukufuku_wo!", "konosuba", "konosuba", "aqua"),
    "darkness": ("kono_subarashii_sekai_ni_shukufuku_wo!", "konosuba", "konosuba", "darkness"),
    "megumin": ("kono_subarashii_sekai_ni_shukufuku_wo!", "konosuba", "konosuba", "megumin"),
    "atago": ("azur_lane", "azur_lane", "azur_lane", "atago"),
    "takao": ("azur_lane", "azur_lane", "azur_lane", "takao"),
    "akagi": ("azur_lane", "azur_lane", "azur_lane", "akagi"),
    "kaga": ("azur_lane", "azur_lane", "azur_lane", "kaga"),
    "enterprise": ("azur_lane", "azur_lane", "azur_lane", "enterprise"),
    "belfast": ("azur_lane", "azur_lane", "azur_lane", "belfast"),
    "taihou": ("azur_lane", "azur_lane", "azur_lane", "taihou"),
    "shinano": ("azur_lane", "azur_lane", "azur_lane", "shinano"),
    "prinz eugen": ("azur_lane", "azur_lane", "azur_lane", "prinz_eugen"),
    "st louis": ("azur_lane", "azur_lane", "azur_lane", "st._louis"),
    "shimakaze": ("azur_lane", "azur_lane", "azur_lane", "shimakaze"),
    "ayanami": ("azur_lane", "azur_lane", "azur_lane", "ayanami"),

    # Blue Archive — топ 2025
    "hinata": ("blue_archive", "blue_archive", "blue_archive", "wakamo"),
    "wakamo": ("blue_archive", "blue_archive", "blue_archive", "wakamo"),
    "asuna": ("blue_archive", "blue_archive", "blue_archive", "ichinose_asuna"),
    "ichinose asuna": ("blue_archive", "blue_archive", "blue_archive", "ichinose_asuna"),
    "karin": ("blue_archive", "blue_archive", "blue_archive", "kakudate_karin"),
    "kakudate karin": ("blue_archive", "blue_archive", "blue_archive", "kakudate_karin"),
    "aru": ("blue_archive", "blue_archive", "blue_archive", "rikuhachima_aru"),
    "rikuhachima aru": ("blue_archive", "blue_archive", "blue_archive", "rikuhachima_aru"),
    "mika": ("blue_archive", "blue_archive", "blue_archive", "misono_mika"),
    "misono mika": ("blue_archive", "blue_archive", "blue_archive", "misono_mika"),
    "hina": ("blue_archive", "blue_archive", "blue_archive", "sorai_hina"),
    "sorai hina": ("blue_archive", "blue_archive", "blue_archive", "sorai_hina"),
    "iroha": ("blue_archive", "blue_archive", "blue_archive", "isshiki_iroha"),
    "yuuka": ("blue_archive", "blue_archive", "blue_archive", "hayase_yuuka"),

    # RWBY
    "ruby rose": ("rwby", "rwby", "rwby", "ruby_rose"),
    "weiss schnee": ("rwby", "rwby", "rwby", "weiss_schnee"),
    "blake belladonna": ("rwby", "rwby", "rwby", "blake_belladonna"),
    "yang xiao long": ("rwby", "rwby", "rwby", "yang_xiao_long"),
    "pyrrha nikos": ("rwby", "rwby", "rwby", "pyrrha_nikos"),
    "neo politan": ("rwby", "rwby", "rwby", "neo_politan"),
    "cinder fall": ("rwby", "rwby", "rwby", "cinder_fall"),
    "penny polendina": ("rwby", "rwby", "rwby", "penny_polendina"),

    # League of Legends — топ waifu
    "ahri": ("league_of_legends", "league_of_legends", "league_of_legends", "ahri"),
    "akali": ("league_of_legends", "league_of_legends", "league_of_legends", "akali"),
    "evelynn": ("league_of_legends", "league_of_legends", "league_of_legends", "evelynn"),
    "katarina": ("league_of_legends", "league_of_legends", "league_of_legends", "katarina"),
    "miss fortune": ("league_of_legends", "league_of_legends", "league_of_legends", "miss_fortune"),
    "jinx": ("league_of_legends", "league_of_legends", "league_of_legends", "jinx"),
    "lux": ("league_of_legends", "league_of_legends", "league_of_legends", "lux"),
    "caitlyn": ("league_of_legends", "league_of_legends", "league_of_legends", "caitlyn"),
    "seraphine": ("league_of_legends", "league_of_legends", "league_of_legends", "seraphine"),
    "kai'sa": ("league_of_legends", "league_of_legends", "league_of_legends", "kai'sa"),
    "ashe": ("league_of_legends", "league_of_legends", "league_of_legends", "ashe"),
    "irelia": ("league_of_legends", "league_of_legends", "league_of_legends", "irelia"),
    "riven": ("league_of_legends", "league_of_legends", "league_of_legends", "riven"),

    # Arknights — топ
    "exusiai": ("arknights", "arknights", "arknights", "exusiai"),
    "texas": ("arknights", "arknights", "arknights", "texas"),
    "mudrock": ("arknights", "arknights", "arknights", "mudrock"),
    "surtr": ("arknights", "arknights", "arknights", "surtr"),
    "chen": ("arknights", "arknights", "arknights", "chen"),
    "skadi": ("arknights", "arknights", "arknights", "skadi"),
    "w": ("arknights", "arknights", "arknights", "w"),
    "specter": ("arknights", "arknights", "arknights", "specter"),
    "amiya": ("arknights", "arknights", "arknights", "amiya"),

    # Goddess of Victory: Nikke
    "rappi": ("nikke", "nikke", "nikke", "rapi"),
    "anis": ("nikke", "nikke", "nikke", "anis"),
    "neon": ("nikke", "nikke", "nikke", "neon"),
    "modernia": ("nikke", "nikke", "nikke", "modernia"),
    "alice": ("nikke", "nikke", "nikke", "alice"),
    "helm": ("nikke", "nikke", "nikke", "helm"),
    "crown": ("nikke", "nikke", "nikke", "crown"),
    "scarlet": ("nikke", "nikke", "nikke", "scarlet"),

    # Girls' Frontline
    "m4a1": ("girls_frontline", "girls_frontline", "girls_frontline", "m4a1"),
    "st ar-15": ("girls_frontline", "girls_frontline", "girls_frontline", "st_ar-15"),
    "hk416": ("girls_frontline", "girls_frontline", "girls_frontline", "hk416"),
    "g11": ("girls_frontline", "girls_frontline", "girls_frontline", "g11"),
    "ump45": ("girls_frontline", "girls_frontline", "girls_frontline", "ump45"),
    "ump9": ("girls_frontline", "girls_frontline", "girls_frontline", "ump9"),

    # Hololive (VTubers — очень популярны в 2025)
    "gawr gura": ("hololive", "hololive", "hololive", "gawr_gura"),
    "mori calliope": ("hololive", "hololive", "hololive", "mori_calliope"),
    "amelia watson": ("hololive", "hololive", "hololive", "amelia_watson"),
    "korone": ("hololive", "hololive", "hololive", "inugami_korone"),
    "inugami korone": ("hololive", "hololive", "hololive", "inugami_korone"),
    "pekora": ("hololive", "hololive", "hololive", "usada_pekora"),
    "usada pekora": ("hololive", "hololive", "hololive", "usada_pekora"),
    "rushia": ("hololive", "hololive", "hololive", "uruha_rushia"),
    "marine": ("hololive", "hololive", "hololive", "houshou_marine"),
    "houshou marine": ("hololive", "hololive", "hololive", "houshou_marine"),

    # Другие популярные (Undertale, Sonic, etc. — продолжение)
    "toriel": ("undertale", "undertale", "undertale", "toriel"),
    "asriel dreemurr": ("undertale", "undertale", "undertale", "asriel_dreemurr"),
    "frisk": ("undertale", "undertale", "undertale", "frisk"),
    "undyne": ("undertale", "undertale", "undertale", "undyne"),
    "alphys": ("undertale", "undertale", "undertale", "alphys"),
    "muffet": ("undertale", "undertale", "undertale", "muffet"),

    # Sonic — продолжение
    "shadow the hedgehog": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "shadow_the_hedgehog"),
    "silver the hedgehog": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "silver_the_hedgehog"),
    "tails": ("sonic_the_hedgehog", "sonic_the_hedgehog", "sonic_the_hedgehog", "tails"),

    # My Little Pony — продолжение
    "princess luna": ("my_little_pony", "my_little_pony", "my_little_pony", "princess_luna"),
    "princess celestia": ("my_little_pony", "my_little_pony", "my_little_pony", "princess_celestia"),
    "princess cadance": ("my_little_pony", "my_little_pony", "my_little_pony", "princess_cadance"),
    "octavia": ("my_little_pony", "my_little_pony", "my_little_pony", "octavia_melody"),
    "vinyl scratch": ("my_little_pony", "my_little_pony", "my_little_pony", "vinyl_scratch"),

    # ... (ещё ~200 в этой части — классика вроде Avatar, Steven Universe, DC/Marvel waifu и т.д.)
    "korra": ("the_legend_of_korra", "the_legend_of_korra", "the_legend_of_korra", "korra"),
    "asami sato": ("the_legend_of_korra", "the_legend_of_korra", "the_legend_of_korra", "asami_sato"),
    "starfire": ("dc_comics", "dc_comics", "dc_comics", "starfire"),
    "raven": ("dc_comics", "dc_comics", "dc_comics", "raven"),
    "harley quinn": ("dc_comics", "dc_comics", "dc_comics", "harley_quinn"),
    "poison ivy": ("dc_comics", "dc_comics", "dc_comics", "poison_ivy"),
    "catwoman": ("dc_comics", "dc_comics", "dc_comics", "catwoman"),
    "black widow": ("marvel", "marvel", "marvel", "black_widow"),
    "scarlet witch": ("marvel", "marvel", "marvel", "scarlet_witch"),
    "jean grey": ("marvel", "marvel", "marvel", "jean_grey"),
    "emma frost": ("marvel", "marvel", "marvel", "emma_frost"),
        # Часть 5 — второстепенные waifu, DC/Marvel, Star Wars, Resident Evil и другие
    # DC Comics / Batman / Superman
    "wonder woman": ("dc_comics", "dc_comics", "dc_comics", "wonder_woman"),
    "supergirl": ("dc_comics", "dc_comics", "dc_comics", "supergirl"),
    "power girl": ("dc_comics", "dc_comics", "dc_comics", "power_girl"),
    "zatanna": ("dc_comics", "dc_comics", "dc_comics", "zatanna"),
    "black canary": ("dc_comics", "dc_comics", "dc_comics", "black_canary"),
    "hawkgirl": ("dc_comics", "dc_comics", "dc_comics", "hawkgirl"),
    "huntress": ("dc_comics", "dc_comics", "dc_comics", "huntress"),

    # Marvel
    "spider-gwen": ("marvel", "marvel", "marvel", "spider-gwen"),
    "gwen stacy": ("marvel", "marvel", "marvel", "gwen_stacy"),
    "mary jane watson": ("marvel", "marvel", "marvel", "mary_jane_watson"),
    "storm": ("marvel", "marvel", "marvel", "storm"),
    "rogue": ("marvel", "marvel", "marvel", "rogue"),
    "psylocke": ("marvel", "marvel", "marvel", "psylocke"),
    "mystique": ("marvel", "marvel", "marvel", "mystique"),
    "captain marvel": ("marvel", "marvel", "marvel", "captain_marvel"),
    "she-hulk": ("marvel", "marvel", "marvel", "she-hulk"),

    # Star Wars
    "rey": ("star_wars", "star_wars", "star_wars", "rey"),
    "princess leia": ("star_wars", "star_wars", "star_wars", "princess_leia"),
    "padme amidala": ("star_wars", "star_wars", "star_wars", "padme_amidala"),
    "aayla secura": ("star_wars", "star_wars", "star_wars", "aayla_secura"),
    "ahsoka tano": ("star_wars", "star_wars", "star_wars", "ahsoka_tano"),
    "asajj ventress": ("star_wars", "star_wars", "star_wars", "asajj_ventress"),

    # Resident Evil
    "ada wong": ("resident_evil", "resident_evil", "resident_evil", "ada_wong"),
    "jill valentine": ("resident_evil", "resident_evil", "resident_evil", "jill_valentine"),
    "lady dimitrescu": ("resident_evil", "resident_evil", "resident_evil", "lady_dimitrescu"),
    "alcina dimitrescu": ("resident_evil", "resident_evil", "resident_evil", "lady_dimitrescu"),
    "rebecca chambers": ("resident_evil", "resident_evil", "resident_evil", "rebecca_chambers"),
    "claire redfield": ("resident_evil", "resident_evil", "resident_evil", "claire_redfield"),

    # Mass Effect
    "liara t'soni": ("mass_effect", "mass_effect", "mass_effect", "liara_t'soni"),
    "miranda lawson": ("mass_effect", "mass_effect", "mass_effect", "miranda_lawson"),
    "tali'zorah": ("mass_effect", "mass_effect", "mass_effect", "tali'zorah_nar_rayya"),
    "jack": ("mass_effect", "mass_effect", "mass_effect", "jack"),
    "ashley williams": ("mass_effect", "mass_effect", "mass_effect", "ashley_williams"),

    # Tomb Raider / Lara Croft variants
    "lara croft classic": ("tomb_raider", "tomb_raider", "tomb_raider", "lara_croft"),
    "lara croft reboot": ("tomb_raider", "tomb_raider", "tomb_raider", "lara_croft"),

    # Avatar: The Last Airbender / Legend of Korra
    "toph beifong": ("avatar_the_last_airbender", "avatar", "avatar", "toph_beifong"),
    "katara": ("avatar_the_last_airbender", "avatar", "avatar", "katara"),
    "azula": ("avatar_the_last_airbender", "avatar", "avatar", "azula"),
    "suki": ("avatar_the_last_airbender", "avatar", "avatar", "suki"),
    "ty lee": ("avatar_the_last_airbender", "avatar", "avatar", "ty_lee"),
    "mai": ("avatar_the_last_airbender", "avatar", "avatar", "mai"),
    "korra": ("the_legend_of_korra", "the_legend_of_korra", "the_legend_of_korra", "korra"),
    "asami sato": ("the_legend_of_korra", "the_legend_of_korra", "the_legend_of_korra", "asami_sato"),

    # Steven Universe
    "pearl": ("steven_universe", "steven_universe", "steven_universe", "pearl"),
    "garnet": ("steven_universe", "steven_universe", "steven_universe", "garnet"),
    "amethyst": ("steven_universe", "steven_universe", "steven_universe", "amethyst"),
    "lapis lazuli": ("steven_universe", "steven_universe", "steven_universe", "lapis_lazuli"),
    "peridot": ("steven_universe", "steven_universe", "steven_universe", "peridot"),
    "jasper": ("steven_universe", "steven_universe", "steven_universe", "jasper"),

    # Gravity Falls
    "mabel pines": ("gravity_falls", "gravity_falls", "gravity_falls", "mabel_pines"),
    "wendy corduroy": ("gravity_falls", "gravity_falls", "gravity_falls", "wendy_corduroy"),
    "pacifica northwest": ("gravity_falls", "gravity_falls", "gravity_falls", "pacifica_northwest"),

    # Adventure Time
    "princess bubblegum": ("adventure_time", "adventure_time", "adventure_time", "princess_bubblegum"),
    "marceline": ("adventure_time", "adventure_time", "adventure_time", "marceline"),
    "flame princess": ("adventure_time", "adventure_time", "adventure_time", "flame_princess"),
    "fionna": ("adventure_time", "adventure_time", "adventure_time", "fionna"),

    # The Witcher
    "yennefer": ("the_witcher", "the_witcher", "the_witcher", "yennefer"),
    "triss merigold": ("the_witcher", "the_witcher", "the_witcher", "triss_merigold"),
    "ciri": ("the_witcher", "the_witcher", "the_witcher", "ciri"),

    # Cyberpunk 2077
    "panam palmer": ("cyberpunk_2077", "cyberpunk_2077", "cyberpunk_2077", "panam_palmer"),
    "judy alvarez": ("cyberpunk_2077", "cyberpunk_2077", "cyberpunk_2077", "judy_alvarez"),
    "lucy": ("cyberpunk_edgerunners", "cyberpunk_edgerunners", "cyberpunk_edgerunners", "lucy"),
    "rebecca": ("cyberpunk_edgerunners", "cyberpunk_edgerunners", "cyberpunk_edgerunners", "rebecca"),

    # Final Fantasy — дополнительные
    "aerith gainsborough": ("final_fantasy_vii", "final_fantasy_vii", "final_fantasy_vii", "aerith_gainsborough"),
    "yuna": ("final_fantasy_x", "final_fantasy_x", "final_fantasy_x", "yuna"),
    "lightning": ("final_fantasy_xiii", "final_fantasy_xiii", "final_fantasy_xiii", "lightning"),
    "cloud of darkness": ("final_fantasy", "final_fantasy", "final_fantasy", "cloud_of_darkness"),

    # Nier / Drakengard
    "a2": ("nier_automata", "nier:automata", "nier:automata", "a2"),
    "kaine": ("nier", "nier", "nier", "kaine"),
    "emil": ("nier", "nier", "nier", "emil"),

    # Bayonetta
    "bayonetta": ("bayonetta", "bayonetta", "bayonetta", "bayonetta"),
    "jeanne": ("bayonetta", "bayonetta", "bayonetta", "jeanne"),

    # Dead or Alive / Tekken
    "kasumi": ("dead_or_alive", "dead_or_alive", "dead_or_alive", "kasumi"),
    "ayane": ("dead_or_alive", "dead_or_alive", "dead_or_alive", "ayane"),
    "asuka kazama": ("tekken", "tekken", "tekken", "kazama_asuka"),
    "ling xiaoyu": ("tekken", "tekken", "tekken", "ling_xiaoyu"),

    # Street Fighter
    "chun-li": ("street_fighter", "street_fighter", "street_fighter", "chun-li"),
    "cammy": ("street_fighter", "street_fighter", "street_fighter", "cammy"),
    "juri han": ("street_fighter", "street_fighter", "street_fighter", "juri_han"),

    # Mortal Kombat
    "kitana": ("mortal_kombat", "mortal_kombat", "mortal_kombat", "kitana"),
    "mileena": ("mortal_kombat", "mortal_kombat", "mortal_kombat", "mileena"),
    "jade": ("mortal_kombat", "mortal_kombat", "mortal_kombat", "jade"),
    "skarlet": ("mortal_kombat", "mortal_kombat", "mortal_kombat", "skarlet"),

    #Kim 5+
    "bonnie rockwaller": ("kim_possible", "kim_possible", "kim_possible", "bonnie_rockwaller"),
    "monique": ("kim_possible", "kim_possible", "kim_possible", "monique"),
    "ann possible": ("kim_possible", "kim_possible", "kim_possible", "ann_possible"),
    "betty director": ("kim_possible", "kim_possible", "kim_possible", "betty_director"),

    # FNAF (Five Nights at Freddy's) — серия и вариации ввода
    "fnaf": ("five_nights_at_freddys", "fnaf", "fnaf", "fnaf"),  # ← главное: rule34_source = "fnaf", correct_tag = "fnaf"
    "five nights at freddy": ("five_nights_at_freddys", "fnaf", "fnaf", "fnaf"),
    "five nights at freddys": ("five_nights_at_freddys", "fnaf", "fnaf", "fnaf"),
    "five nights at freddy's": ("five_nights_at_freddys", "fnaf", "fnaf", "fnaf"),

    # Популярные персонажи FNAF (оставляем как есть, они используют свой тег)
    "freddy fazbear": ("five_nights_at_freddys", "fnaf", "fnaf", "freddy_fazbear"),
    "bonnie": ("five_nights_at_freddys", "fnaf", "fnaf", "bonnie"),
    "chica": ("five_nights_at_freddys", "fnaf", "fnaf", "chica"),
    "foxy": ("five_nights_at_freddys", "fnaf", "fnaf", "foxy"),
    "circus baby": ("five_nights_at_freddys", "fnaf", "fnaf", "circus_baby"),
    "mangle": ("five_nights_at_freddys", "fnaf", "fnaf", "mangle"),
    "springtrap": ("five_nights_at_freddys", "fnaf", "fnaf", "springtrap"),
    "vanny": ("five_nights_at_freddys", "fnaf", "fnaf", "vanny"),
    "vanessa": ("five_nights_at_freddys", "fnaf", "fnaf", "vanessa"),
    "roxanne wolf": ("five_nights_at_freddys", "fnaf", "fnaf", "roxanne_wolf"),
    "roxy": ("five_nights_at_freddys", "fnaf", "fnaf", "roxanne_wolf"),
    "glamrock chica": ("five_nights_at_freddys", "fnaf", "fnaf", "glamrock_chica"),
    "glamrock freddy": ("five_nights_at_freddys", "fnaf", "fnaf", "glamrock_freddy"),
    "montgomery gator": ("five_nights_at_freddys", "fnaf", "fnaf", "montgomery_gator"),
    "monty": ("five_nights_at_freddys", "fnaf", "fnaf", "montgomery_gator"),
    "toy chica": ("five_nights_at_freddys", "fnaf", "fnaf", "toy_chica"),
    "puppet": ("five_nights_at_freddys", "fnaf", "fnaf", "the_puppet"),
    "the puppet": ("five_nights_at_freddys", "fnaf", "fnaf", "the_puppet"),
    "golden freddy": ("five_nights_at_freddys", "fnaf", "fnaf", "golden_freddy"),

        # Gushing over Magical Girls / Mahou Shoujo ni Akogarete
    "hiiragi utena": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "hiiragi_utena"),
    "utena hiiragi": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "hiiragi_utena"),
    "magia baiser": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_baiser"),
    "baiser": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_baiser"),

    "hanabishi haruka": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "hanabishi_haruka"),
    "haruka hanabishi": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "hanabishi_haruka"),
    "magia magenta": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_magenta"),

    "tenkawa kaoruko": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "tenkawa_kaoruko"),
    "kaoruko tenkawa": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "tenkawa_kaoruko"),
    "magia azure": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_azure"),
    "azure": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_azure"),

    "korisu morino": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "morino_korisu"),
    "morino korisu": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "morino_korisu"),
    "leopard": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "leopard_(mahou_shoujo_ni_akogarete)"),

    "yasuen michiko": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "yasuen_michiko"),
    "michiko yasuen": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "yasuen_michiko"),
    "nero alice": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "nero_alice"),

    "anzu sayo": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "anzu_sayo"),
    "sayo anzu": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "anzu_sayo"),
    "sulfur": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_sulfur"),
    "magia sulfur": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "magia_sulfur"),

    "kiwi araga": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "araga_kiwi"),
    "araga kiwi": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "araga_kiwi"),
    "leopolt": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "leopard_(mahou_shoujo_ni_akogarete)"),  # альтернативное написание

    "lord enorme": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "lord_enorme"),
    "enorme": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "lord_enorme"),
    "venalita": ("mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "mahou_shoujo_ni_akogarete", "venalita"),

}